### ISSUE TITLE
Cadastre tutorial: Remove "$" in the bash examples

### ISSUE THREAD

**Issue by fnicollet** [Melown/workshop#10]
Hello,

The cadastre tutorial is a little inconsistent concerning the snippets of bash code to copy. Sometimes it starts with a $, sometimes it doesn't appear.

I think the tutorial should do one or the other but not a mix. My personal opinion, remove them altogether, makes it easier to copy to clipboard.

Also, the JSON bit with the comments (# where is our storage...) should appear twice, one without the comments (easy to copy) and one with the comments (easy to understand) and it is quite annoying to remove those comments depending on the editor you use (I use vim here)

Thanks,

**Comment by ladislavhorky** [comment]
Fixed in 372e537d20df08065861acc18fa26c4895341090.

**Comment by fnicollet** [comment]
Excellent 👍
