### ISSUE TITLE
Cadastre tutorial: Typo jentejn-village / jenstejn-village

### ISSUE THREAD

**Issue by fnicollet** [Melown/workshop#11]
The --add tilesets says "jentejn-village" (missing "s"):
http://melown.readthedocs.io/en/latest/tutorials/cadastre.html#adding-tilesets-into-storage

but vef2vts uses "jenstejn-village":
http://melown.readthedocs.io/en/latest/tutorials/cadastre.html#preparing-true3d-tilesets

 Probably just a typo, but that would explain the errors I get on those datasets

Fabien

**Comment by ladislavhorky** [comment]
Fixed in bcea88ce88b913ac291f168f44bbc9f8ad47ee14. There were few more of them. Thanks for pointing that out.

**Comment by fnicollet** [comment]
👍
