### ISSUE TITLE
How do I use a custom shader?

### ISSUE THREAD

**Issue by TriangularPainter** [Melown/workshop#26]
For learning purposes, I'm going to draw a red triangle using a custom shader.
but It doesn't render anything.

1. the mesh:
`var mesh = renderer.createMesh({ vertices: [ 0, 0,  0, 0.5,  0.7, 0], vertexSize: 2 })`

2. the shader:

vs: 
        
         attribute vec4 aPosition; 

         void main() {

                gl_Position = aPosition;

         }

fs:

         precision mediump float;

            void main() {
        
                gl_FragColor = vec4(1.0, 0.0, 0.0, 1.0); 
            }

3. draw call:

          renderer.drawMesh({

               mesh: model,
               shader: shader,
               shaderVariables : {
               
            }
        })

[demo link](https://github.com/melowntech/workshop/issues/26)

**Comment by ladislavhorky** [comment]
Hello,
are you following any of [vts-geospatial](https://vts-geospatial.org/tutorials/index.html) tutorials? I would be glad to help if provide some more context (what are you trying to achieve? The VTS Geospatial is a 3D virtual landscape streaming and rendering platform). 

Depending on if you are using out [C++](https://github.com/melowntech/vts-browser-cpp) or [JavaScript](https://github.com/melowntech/vts-browser-js) clients, you might consider posting issue there.

**Comment by TriangularPainter** [comment]
> Hello,
> are you following any of [vts-geospatial](https://vts-geospatial.org/tutorials/index.html) tutorials? I would be glad to help if provide some more context (what are you trying to achieve? The VTS Geospatial is a 3D virtual landscape streaming and rendering platform).
> 
> Depending on if you are using out [C++](https://github.com/melowntech/vts-browser-cpp) or [JavaScript](https://github.com/melowntech/vts-browser-js) clients, you might consider posting issue there.

oh sorry, I put it in the wrong place,  I focused on searching for the answer to the question
