### ISSUE TITLE
Agisoft Tls format?

### ISSUE THREAD

**Issue by jrjdavidson** [Melown/workshop#30]
Hello,

what encoder do i need to use to process a agisoft tls format file? Or should i export from agisoft in a different format? I know that melown cloud processes them, so it should be possible!

Thanks,
JD

**Comment by ladislavhorky** [comment]
Hello Jonathan,

The TLS is Agisoft's internal format not natively supported by VTS. 

However, Metashape is able to export **3DTiles** for some time, that can be converted to VTS via `3dtiles2vts` commandline tool available in `vts-backend` Debian package - tutorial [here](https://vts-geospatial.org/tutorials/vtsbackend.html#install-vts-backend).

**Comment by jrjdavidson** [comment]
thanks!
