### ISSUE TITLE
Error in "cadastre" tutorial when using mapproxy-tiling (failed to open dataset)

### ISSUE THREAD

**Issue by fnicollet** [Melown/workshop#6]
Hello,

I am trying the tutorials, but when it comes to:
```
 mapproxy-tiling --input srtm --lodRange 9,15 --tileRange 137,85:138,86 --referenceFrame melown2015
```
I get the following error:
```
vts@BG-test-soft-3D-FN:~/mapproxy/datasets$ mapproxy-tiling --input srtm --lodRange 9,15 --tileRange 137,85:138,86 --referenceFrame melown2015
2017-07-24 15:57:56 I3 [2529(main)]: [mapproxy-tiling] Config:
        input = "srtm"
        dataset = ""
        output = "srtm/tiling.melown2015"
        referenceFrame = melown2015
        lodRange = 9,15
        tileRange = 137,85:138,86
 {main.cpp:configure():253}
2017-07-24 15:57:56 E2 [2529(main)]: gdal error 4: : No such file or directory {geodataset.cpp:GDALErrorHandler():71}
2017-07-24 15:57:56 E2 [2529(main)]: Failed to open dataset "". {geodataset.cpp:open():327}
```
Input is set but dataset isn't. In the "--help", there no option for passing a dataset or anything (not sure what I would input anyway)

Is this a known issue?

Thanks,
Fabien

**Comment by ladislavhorky** [comment]
Hi Fabien,

it looks like some clash of paths that was created by me and my colleague. Basically all SRTM data should be under ```/var/vts/mapproxy/datasets/srtm/``` but now they are not. Let me go through it and fix the paths.

NB:
The ```mapproxy-tiling``` needs to be run with ```--input``` pointing to the directory that contains ```dem```, ```dem.min``` and ```dem.max``` symlinks and this path also goes to the mapproxy configuration snippet (```"dataset" : "srtm"```).

Thanks for contribution,
Ladislav

**Comment by fnicollet** [comment]
ok, I thought that the directory structure it created didn't make much sense, thanks for your help!

**Comment by ladislavhorky** [comment]
Hi, so the section [Setting up dynamic surfaces](https://melown.readthedocs.io/en/latest/tutorials/cadastre.html#setting-up-dynamic-surfaces) has been fixed in https://github.com/Melown/workshop/commit/2ae1b18d2b0fb9035ddbfcc016b357050b8eaf0d .

Tomorrow I'll go through the rest of the tutorial to make it look more BASHy and more suitable for copy-pasting.

**Comment by fnicollet** [comment]
awesome, i'll continue my copy-pasting then, i'll open some PR/issues if I notice anything
