### ISSUE TITLE
Cadastre tutorial: mapy-cz-ophoto/boundlayer.json not found?

### ISSUE THREAD

**Issue by fnicollet** [Melown/workshop#8]
Hello,

I went through the tutorial and launched the JS viewer, but I get some errors in the console:
```
http://10.1.21.210:8070/mapproxy/melown2015/tms/cadastre/mapy-cz-ophoto/boundlayer.json
```
This file is 404. In the "cadastre" map-config, there is indeed a reference to that file:
```
"boundLayers": {                  
              "mapy-cz": "/mapproxy/melown2015/tms/cadastre/mapy-cz-ophoto/boundlayer.json",
              "cadastre-raster": "/mapproxy/melown2015/tms/cadastre/cuzk-raster-cadastre/boundlayer.json"
      },
```
But in the "Setting up bound layers" part, it says to add the JSON bit to resources.json, the boundlayer.json never seem to be created anywhere?

Then, I am also getting some others 404, such as:
```
http://10.1.21.210:8070/store/stage.melown2015/tilesets/jenstejn-village/0-0-0.meta?0
```
But that might be normal

Thanks for your help,
Fabien

**Comment by ladislavhorky** [comment]
Hi, the ```boundlayer.json``` is served dynamically by mapproxy once it successfully configures the resource.  Did you check the ```/var/log/vts/mapproxy.log```? If the configuration is successful, the should be a line like this:

    Ready to serve <cadastre/mapy-cz-ophoto> ... 

If there is one, there might be something wrong on the path from the browser to the mapproxy. 
Regarding the second case, can you browse the following address (should give you just directory tree)?

    http://10.1.21.210:8070/store/

**Comment by fnicollet** [comment]
Ok, nevermind, somehow I didn't copy the JSON definition of this layer in resources.json. Added it back and now the file is found.
Thanks for the advices on where to look :)

Fabien
